### ISSUE TITLE
Leak of personal access tokens and private keys

### ISSUE THREAD

**Issue by madnight** [ibrokemypie/dotfiles#1]
Hi, you should check your uploaded dotfiles, it seems like you uploaded private token and private keys as for example:
https://github.com/ibrokemypie/dotfiles/tree/master/.gnupg/private-keys-v1.d/private-keys-v1.d. 
https://github.com/ibrokemypie/dotfiles/blob/master/.weechat/sec.conf. 

Please note that removing this files would not be enough, you need to change the tokens and generate new keys.

**Comment by ibrokemypie** [comment]
well shit

**Comment by Johnnynator** [comment]
and you also have your damn password in these files...
and you also may should go with an more secure and longer password instead of onw word and 4 repetitive numbers...

**Comment by ibrokemypie** [comment]
@NeoChontrix which files have/had that password? very old so probably wasnt even working when it was uploaded, though I am curious just in case I hadnt changed it for whatever service that was.

**Comment by Johnnynator** [comment]
*hust* old *hust* it is you current git pasword in 
https://github.com/ibrokemypie/dotfiles/blob/master/.gitconfig

**Comment by ibrokemypie** [comment]
thankyou both for bringing this to my attention, I have removed these files from the entire history, as well as other I have found, and have updated the gitignore accordingly, as well as changed effected keys and passwords. will be a lot more attentive to what I add from now on.

**Comment by Johnnynator** [comment]
No problem, I hope you have choosen a more secure password.
